################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
App/ap \
App/bsp \
App/common/core \
App/common/hw/src \
App/hw/driver \
App/hw/driver/touch \
App/hw \
Core/Src \
Core/Startup \
Drivers/STM32H7xx_HAL_Driver/Src \
TouchGFX/App \
TouchGFX/build/App/ap/modules \
TouchGFX/build/App/common/core \
TouchGFX/build/MINGW32_NT-6.2/generated/fonts/src \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/adminsetupscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/common \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/containers \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/factorysetupscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/historyscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/initscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/mainscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/rtouchcalibrationscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/screenkeyboard_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/setupscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/systeminfoscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/timesetupscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/zeroadjustscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src/__designer \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src/__generated \
TouchGFX/build/MINGW32_NT-6.2/generated/simulator/src \
TouchGFX/build/MINGW32_NT-6.2/generated/simulator/src/video \
TouchGFX/build/MINGW32_NT-6.2/generated/texts/src \
TouchGFX/build/MINGW32_NT-6.2/gui/src/adminsetupscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/common \
TouchGFX/build/MINGW32_NT-6.2/gui/src/containers \
TouchGFX/build/MINGW32_NT-6.2/gui/src/factorysetupscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/historyscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/initscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/mainscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/model \
TouchGFX/build/MINGW32_NT-6.2/gui/src/rtouchcalibrationscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/screenkeyboard_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/setupscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/systeminfoscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/timesetupscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/zeroadjustscreen_screen \
TouchGFX/build/MINGW32_NT-6.2/hal/ap \
TouchGFX/build/MINGW32_NT-6.2/hal/bsp \
TouchGFX/build/MINGW32_NT-6.2/hal/hw/driver \
TouchGFX/build/MINGW32_NT-6.2/hal/hw \
TouchGFX/build/MINGW32_NT-6.2/simulator \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/driver/touch \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/hal/simulator/sdl2 \
TouchGFX/generated/fonts/src \
TouchGFX/generated/gui_generated/src/common \
TouchGFX/generated/gui_generated/src/screen_screen \
TouchGFX/generated/images/src \
TouchGFX/generated/texts/src \
TouchGFX/gui/src/common \
TouchGFX/gui/src/model \
TouchGFX/gui/src/screen_screen \
TouchGFX/target \
TouchGFX/target/generated \

